### ISSUE TITLE
Multiple feeds

### ISSUE THREAD

**Issue by git-scott** [MarshalX/bluesky-feed-generator#11]
Hi, thanks for the python implementation.  I have a feed running and would like to generate and serve more feeds from the same firehose.  I feel like I’m missing something obvious here, but is it trivial to implement multiple feeds with the existing code?  I assume I can create as many algo’s as I need, but I’m having trouble getting my head round how the filter should be set up for this. Does the existing logic easily accomodate multiple feeds?

**Comment by MarshalX** [comment]
Hi! With my pleasure! Yes, it's possible. You should add a new column “feed” if it does not exist. And save posts to DB with the new value. 

Like this:

If Alf in text: savePost(alfFeed, post)

If Sky in text: savePOST(skyFeed, post)

**Comment by git-scott** [comment]
Excellent, many thanks! :)
