### ISSUE TITLE
Parsing Alt Text

### ISSUE THREAD

**Issue by git-scott** [MarshalX/bluesky-feed-generator#12]
Hi, sorry for the novice question but I’m struggling to work out how to access alt-text for embedded images in posts.  How is this done, assuming there may be multiple images’ text to parse per post.

Thanks

**Comment by MarshalX** [comment]
Hi, in `data_filter.py` line no 22 you can add this one:

```python
if post_with_images:
    for image in record.embed.images:
        print('Alt:', image.alt)
```

**Comment by git-scott** [comment]
Thanks very much!
