### ISSUE TITLE
"Could not resolve identity"

### ISSUE THREAD

**Issue by Menakoy** [MarshalX/bluesky-feed-generator#13]
I recently switched my feed from the starter kit to this implementation but trying to look at the feed just gives the error "could not resolve identity did:web:[etc]"  

any ideas what may be the issue?

Everything is running on https and I can reach all the endpoints through the domain.

**Comment by MarshalX** [comment]
Hi, pls share the domain and the published feed

**Comment by Menakoy** [comment]
Oh yeah sorry. The domain is dongfeed.xyz and the feed is at https://bsky.app/profile/did:plc:q2tafhcn2shp2awi2i7temfg/feed/fantasy-toys

and yes the feed is for what it sounds like sorry for subject matter.

Heres also a screenshot of the error on my end

![image](https://github.com/MarshalX/bluesky-feed-generator/assets/77512490/59bc43cc-117a-4c4c-9d17-b2a84294b7f5)

**Comment by MarshalX** [comment]
@Menakoy i tried to resolve your did using python resolver and this is what i except:

```python
from atproto import IdResolver
print(IdResolver().did.resolve('did:web:feed.atproto.blue'))
# id='did:web:feed.atproto.blue' also_known_as=None verification_method=None service=[Service(id='#bsky_fg', type='BskyFeedGenerator', service_endpoint='https://feed.atproto.blue')]
```

and this is what i get from your domain:
```python
from atproto import IdResolver
print(IdResolver().did.resolve('did:web:dongfeed.xyz'))
# ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)
# Error resolving DID did:web:dongfeed.xyz
```

it open for me in browser (firefox) too. but something with SSL for sure

**Comment by Menakoy** [comment]
I fixed the SSL error and am able to successfully resolve it using the python resolver 

`id='did:web:dongfeed.xyz' also_known_as=None verification_method=None service=[Service(id='#bsky_fg', type='BskyFeedGenerator', service_endpoint='https://dongfeed.xyz')]`

However I'm now getting an invalid request error on the feed

**Comment by Menakoy** [comment]
Nevermind it was just an error in my .env left over from experimenting!

Thanks so much
