### ISSUE TITLE
SubscriptionState cursor defaults to only a 32-bit integer with PostgreSQL and MySQL databases

### ISSUE THREAD

**Issue by emilyhunt** [MarshalX/bluesky-feed-generator#15]
This is a small issue that might help stop someone running into the same [firehose cursor issue](https://bsky.app/profile/emily.space/post/3latsiuut2c2b) I had today.

Basically, the project defaults to using a local SQLite database. SQLite integers are 64 bit by default (I think). However, I changed my project to use MySQL for compatibility with my hosting. MySQL integer fields default to 32 bit, which is too small for the current Bluesky cursor, which has gotten bigger than that value.

I'd propose changing the following in database.py:

```
class SubscriptionState(BaseModel):
    service = peewee.CharField(unique=True)
    cursor = peewee.IntegerField()
```

to instead have a BigIntegerField for the cursor. This changes nothing for the default SQLite ([peewee](https://docs.peewee-orm.com/en/latest/peewee/models.html) will store it as the same type - just an integer), but means the cursor will be storable if someone uses the project but changes the database type.

PR to follow =)

**Comment by MarshalX** [comment]
amazing, thank you!
