### ISSUE TITLE
Feed stops receiving new posts after about 8 hours

### ISSUE THREAD

**Issue by seanthegeek** [MarshalX/bluesky-feed-generator#19]
Hello. When using this template, I've noticed that it will stop receiving new posts after about 8 hours like clockwork until I restart the service. The service will try to load the posts that it missed in the meantime, but it can never catch up, so I delete the feed database before starting the service again.

I'm not sure if some sort of keepalive needs to happen and/or more graceful error handling.

I'm attaching two tracebacks, although this last time I noticed that there was no exception or traceback generated when the feed stopped receiving posts.

[bluesky.log](https://github.com/user-attachments/files/18039381/bluesky.log)

**Comment by MarshalX** [comment]
Hello. As I can see from your logs it is this issue https://github.com/MarshalX/atproto/issues/430

**Comment by seanthegeek** [comment]
I still have an issue with the feed occasionally not having any new posts until the server is restarted. This time it is not related to that other issue, because there are no errors or earnings in the logs. I'm still researching the cause.

**Comment by p1timmy** [comment]
> I still have an issue with the feed occasionally not having any new posts until the server is restarted.

I had that same exact issue too and found out it's caused by a bug in the ATproto SDK code where there's no timeout in receiving messages, I filed an issue about it in MarshalX/atproto#489

**Comment by seanthegeek** [comment]
Turns out this was a client-side issue.

**Comment by MarshalX** [comment]
@seanthegeek could you share more details? For others

**Comment by seanthegeek** [comment]
[deck.blue](https://deck.blue) sometimes won't updated the feed automatically like it should until the page it refreshed.
