### ISSUE TITLE
Error on feed example

### ISSUE THREAD

**Issue by IamC8** [MarshalX/bluesky-feed-generator#2]
Hi. I'm new to bsky. Came across your code when looking at AT Protocol

Your Feed example: https://bsky.app/profile/did:plc:kvwvcn5iqfooopmyzvb4qzba/feed/whats-alf
gives error:
could not resolve did document: did:web:feed.atproto.blue

Is this a bksy issue?

**Comment by MarshalX** [comment]
Hi. I don't run this example feed anymore. Sorry
