### ISSUE TITLE
Question about whether I'm doing this correctly

### ISSUE THREAD

**Issue by venteto** [MarshalX/bluesky-feed-generator#9]
I have a [repo](https://github.com/venteto/apsfd) with a screenshot of the results of the script.

I was trying to create a script to permanently delete a custom feed that was created using SkyFeed. Other feeds I had created with SkyFeed were successfully A) unpublished and then B) deleted without any lingering artifacts. But this particular "zombie" feed references in my repo won't go away, it keeps lingering to just be re-published and un-published, over and over.

In my script, I'm not sure if:

- I have entered the correct value for `RECORD_NAME`
- where I might obtain the correct value
- whether I need additional code
- or if what I want to do is actually achievable given that the feed was created on SkyFeed; I don't know which server holds the zombie "record" of my unpublished feed for instance

Thank you for any insight.

**Comment by MarshalX** [comment]
hi could you provide uri for such feed? i can't find it in your bsky profile

**Comment by MarshalX** [comment]
1. looks legit
2. last part of the url. for example for "https://bsky.app/profile/did:plc:s6jnht6koorxz7trghirytmf/feed/atproto" it's "atproto"
3. one call of "delete_record" is enough
4. i know nothing about SkyFeed. in my opinion, you should delete the first feed from SkyFeed and after that delete the record in atproto. deleting the record is enough overall by such services likes SkyFeed can handle it like "if there is no feed record create identical one"

**Comment by venteto** [comment]
Thanks for your help, I guess there's nothing I can really do. I've tried deleting them from the SkyFEED UI multiple times over (weeks since Bluesky unveiled curated user lists). Some of them I had no problem completely deleting, but these two won't go away. Two different results, in the same UI, and the SkyFeed developer really doesn't have much to say about it, so I was trying to find a way to delete them outside of SkyFeed.
